# CamlGI configuration                                -*- Makefile -*-
# Copyright (C) Christophe TROESTLER
#	$Id: Makefile.config,v 1.6 2005/06/12 21:46:50 chris_77 Exp $	
#
# $(PKGNAME) and $(PKGVERSION) are defined.

# OCAMLC, OCAMLOPT, OCAMLDEP, OCAMLDOC
# The location of the OCaml compiler and tools. The defaults should be OK.
#
OCAMLC	 = ocamlc
OCAMLOPT = ocamlopt
OCAMLDEP = ocamldep
OCAMLDOC = ocamldoc
OCAMLFIND = ocamlfind

PREFIX=/usr/local
#PREFIX=/usr/local/stow/ocaml-$(PKGNAME)-$(PKGVERSION)

# OCAMLLIBDIR: location of OCaml's library files.
# Set it if you want another directory than the default findlib directory.
#OCAMLLIBDIR = $(PREFIX)/lib/ocaml/$(shell ocamlc -version)

# DOCDIR: where we will install the documentation.
#
DOCDIR = $(PREFIX)/doc/$(PKGNAME)-$(PKGVERSION)

# Utilities
#
COPY = cp
#COPY = copy
REMOVE = rm
